[package]
name = "uair"
version = "0.6.1"
authors = ["Rishabh Das <rdas@tutanota.com>"]
edition = "2021"
description = "An extensible pomodoro timer"
license = "MIT"
repository = "https://github.com/metent/uair/"
keywords = ["pomodoro", "timer", "countdown", "cli", "productivity"]
categories = ["command-line-utilities"]

[dependencies]
argh = "0.1.10"
async-io = "1.13.0"
async-net = "1.7.0"
bincode = "1.3.3"
futures-lite = "1.13.0"
humantime = "2.1.0"
humantime-serde = "1.1.1"
log = "0.4.19"
serde = { version = "1.0.164", features = ["derive"] }
signal-hook = "0.3.15"
signal-hook-async-std = "0.2.2"
simplelog = "0.12.1"
sysinfo = "0.29.10"
thiserror = "1.0.40"
toml = "0.7.5"
winnow = "0.5.0"

[profile.release]
opt-level = "z"     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = "abort"     # Abort on panic
strip = true        # Automatically strip symbols from the binary.
